backend:
  name: github
  repo: bngocchau93-commits/2kay-official
  branch: main

media_folder: "assets"
public_folder: "assets"

collections:
  # --- SECTION 1: LORE & DEVLOG MANAGEMENT ---
  - name: "lore"
    label: "Lore & Devlogs"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "Sam" }
      - { label: "External Link (AO3/etc.)", name: "link", widget: "string", required: false }
      - { label: "Body Content", name: "body", widget: "markdown" }

  # --- SECTION 2: GALLERY MANAGEMENT ---
  - name: "gallery"
    label: "Gallery & Artworks"
    folder: "_gallery"
    create: true
    slug: "art-{{fields.title}}"
    fields:
      - { label: "Artwork Title (Vi du: Art 5)", name: "title", widget: "string" }
      - { label: "Upload Image", name: "image", widget: "image" }
      # ---  PROJECT ---
      - { 
          label: "Project", 
          name: "project", 
          widget: "select", 
          options: ["Wandering Relics", "PJ 02", "PJ 03"] 
        }
      - { label: "Artist Description", name: "description", widget: "text", required: false }
  # --- SECTION 3: EVENT MANAGEMENT ---
  - name: "events"
    label: "Events & Broadcasts"
    folder: "_events"
    create: true
    slug: "event-{{year}}-{{month}}-{{day}}"
    fields:
      - { label: "Event Title", name: "title", widget: "string" }
      - { label: "Date & Time", name: "date", widget: "datetime" }
      - { label: "Category", name: "category", widget: "select", options: ["Studio Event / Giveaway", "Streamer Live Broadcast"] }
      - { label: "Short Description", name: "description", widget: "text" }
      - { label: "Action Link (Twitch/YouTube/Form)", name: "link", widget: "string", required: false }
